### ISSUE TITLE
iPhone newer iOS version

### ISSUE THREAD

**Issue by geani** [kevinbungeneers/nhc-homekit#6]
hello
running iOS 11.3. 

home control stopped working, 

any idees?

**Comment by kevinbungeneers** [comment]
Did you do a clean install of iOS? Because if you did, you might need to initiate the pairing process again.

**Comment by geani** [comment]
Had to update homebridge. Then it worked perfectly. 

Upgrading my installation with a connected controller version 2 this week Dont know if you heard of it. Hopefully it Will stil work because i think interface Will be completely different .
Dont know if u have something on paper like tutorial on how you did you’re research of version 1. Connecting to it and stuff

**Comment by kevinbungeneers** [comment]
Ok cool!

I pretty much reverse-engineered this stuff by trial and error and using wireshark to see what was actually happening. I could always give pointers and try to help you out if you have any specific problems or questions.

My guess is it'll still work, unless they added encryption to the mix, like Loxone does (iirc).

**Comment by geani** [comment]
So installed the new connected controller module. Nice Changes and Niko app works faster, 

BUT 

Nhc-HomeKit not working, didn’t have a full look at it yet, thought maybe you could see where problem is because you Made this,

This is the error

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 192.168.0.227:8000
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)


So my guess its because everythings build in one module and I think the server addresses changed. So have to reconfigure connection to it.

Hope you have any idea

Grtz

**Comment by kevinbungeneers** [comment]
I honestly have no clue. It could be that the controller does its work on another port, or maybe Niko implemented some kind of encryption? With Wireshark you can sniff your home network to see what exactly is going on.

There's not much I can do to help without any hardware to test this with, sorry!

**Comment by geani** [comment]
hello, started looking again for the problem, but to be honest I'm quite the noob here

how can you change the port in you're configuration? searched everywhere
